table YieldBySiteByDate

	column YieldBySiteByDate
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		summarizeBy: none
		sourceColumn: YieldBySiteByDate

		annotation SummarizationSetBy = User

	column Asset
		dataType: string
		summarizeBy: none
		sourceColumn: Asset

		annotation SummarizationSetBy = Automatic

	column Site
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: Site

		annotation SummarizationSetBy = Automatic

	column DateByTurn
		dataType: dateTime
		formatString: Long Date
		summarizeBy: none
		sourceColumn: DateByTurn

		variation Variation
			isDefault
			relationship: 0e65d1f7-4444-44ec-9481-bade4f25135a
			defaultHierarchy: LocalDateTable_c97ca8a6-3dd6-4cd6-9161-1e0699efd275.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DateKeyByTurn
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: DateKeyByTurn

		annotation SummarizationSetBy = Automatic

	partition YieldBySiteByDate-c93261dd-642f-4297-83c4-36958e2e5242 = m
		mode: import
		source =
				let
				    Source = SRMP_RawDataSummarized,
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"YieldBySiteByDate", "Asset", "DateByTurn", "DateKeyByTurn", "Site"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns")
				in
				    #"Removed Duplicates"

	annotation PBI_ResultType = Table

