table YieldByAssetByHour

	column Asset
		dataType: string
		summarizeBy: none
		sourceColumn: Asset

		annotation SummarizationSetBy = Automatic

	column YieldByAssetByHour
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		summarizeBy: sum
		sourceColumn: YieldByAssetByHour

		annotation SummarizationSetBy = Automatic

	column TestHour
		dataType: dateTime
		formatString: Long Time
		summarizeBy: none
		sourceColumn: TestHour

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column DateByTurn
		dataType: dateTime
		formatString: Long Date
		summarizeBy: none
		sourceColumn: DateByTurn

		variation Variation
			isDefault
			relationship: c0a6b2d8-cde6-458f-9dbf-2390339906cd
			defaultHierarchy: LocalDateTable_00bee1dd-6a91-432e-a06f-13ffe99a58d2.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DateKeyByTurn
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: DateKeyByTurn

		annotation SummarizationSetBy = Automatic

	partition YieldByAssetByHour-89adf56b-622a-46bf-bf58-5d8707f3799a = m
		mode: import
		source =
				let
				    Source = SRMP_RawDataSummarized,
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"Asset", "YieldByAssetByHour", "DateByTurn", "DateKeyByTurn", "TestHour"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns")
				in
				    #"Removed Duplicates"

	annotation PBI_ResultType = Table

