table Reseller

	column ResellerKey
		dataType: int64
		isHidden
		formatString: 0
		summarizeBy: none
		sourceColumn: ResellerKey

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation PBI_ChangedProperties = ["IsHidden"]

	column 'Business Type'
		dataType: string
		summarizeBy: none
		sourceColumn: Business Type

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

	column Reseller
		dataType: string
		isDefaultLabel
		summarizeBy: none
		sourceColumn: Reseller

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

	column City
		dataType: string
		dataCategory: City
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

	column State-Province
		dataType: string
		dataCategory: StateOrProvince
		summarizeBy: none
		sourceColumn: State-Province

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

	column Country-Region
		dataType: string
		dataCategory: County
		summarizeBy: none
		sourceColumn: Country-Region

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

	column 'Postal Code'
		dataType: string
		dataCategory: PostalCode
		summarizeBy: none
		sourceColumn: Postal Code

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

	column 'Reseller ID'
		dataType: string
		summarizeBy: none
		sourceColumn: Reseller ID

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

	hierarchy Geography

		level Country-Region
			column: Country-Region

		level State-Province
			column: State-Province

		level City
			column: City

		level 'Postal Code'
			column: 'Postal Code'

		level Reseller
			column: Reseller

	partition Reseller-e44d0a71-e144-4c32-b1af-2f758a686c3c = m
		mode: import
		source =
				let
				    Source = Sql.Database(SqlServerInstance, SqlServerDatabase),
				    dbo_DimReseller = Source{[Schema="dbo",Item="DimReseller"]}[Data],
				    #"Removed Other Columns" = Table.SelectColumns(dbo_DimReseller,{"ResellerKey", "ResellerAlternateKey", "BusinessType", "ResellerName", "DimGeography"}),
				    #"Expanded DimGeography" = Table.ExpandRecordColumn(#"Removed Other Columns", "DimGeography", {"City", "StateProvinceName", "EnglishCountryRegionName", "PostalCode"}, {"City", "StateProvinceName", "EnglishCountryRegionName", "PostalCode"}),
				    #"Add NA Row" = Table.InsertRows(#"Expanded DimGeography", 0, {[ResellerKey = -1, ResellerAlternateKey = "[Not Applicable]", BusinessType = "[Not Applicable]", ResellerName = "[Not Applicable]", City = "[Not Applicable]", StateProvinceName ="[Not Applicable]", EnglishCountryRegionName ="[Not Applicable]", PostalCode ="[Not Applicable]"]}),
				    #"Renamed Columns" = Table.RenameColumns(#"Add NA Row",{{"ResellerAlternateKey", "Reseller ID"}, {"BusinessType", "Business Type"}, {"ResellerName", "Reseller"}, {"StateProvinceName", "State-Province"}, {"EnglishCountryRegionName", "Country-Region"}, {"PostalCode", "Postal Code"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

