table Sales

	measure 'Total Sales Amount' = SUM(Sales[Sales Amount])
		formatString: "£"#,0.###############;-"£"#,0.###############;"£"#,0.###############

		annotation Format = <Format Format="CurrencyGeneral" ThousandSeparator="True"><Currency LCID="2057" DisplayName="£ English (United Kingdom)" Symbol="£" PositivePattern="0" NegativePattern="1" /></Format>

	column SalesOrderLineKey
		dataType: int64
		isHidden
		formatString: 0
		summarizeBy: none
		sourceColumn: SalesOrderLineKey

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation PBI_ChangedProperties = ["IsHidden"]

	column ResellerKey
		dataType: int64
		isHidden
		formatString: 0
		summarizeBy: none
		sourceColumn: ResellerKey

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation PBI_ChangedProperties = ["IsHidden"]

	column CustomerKey
		dataType: int64
		isHidden
		formatString: 0
		summarizeBy: none
		sourceColumn: CustomerKey

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation PBI_ChangedProperties = ["IsHidden"]

	column ProductKey
		dataType: int64
		isHidden
		formatString: 0
		summarizeBy: none
		sourceColumn: ProductKey

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation PBI_ChangedProperties = ["IsHidden"]

	column OrderDateKey
		dataType: int64
		isHidden
		formatString: 0
		summarizeBy: none
		sourceColumn: OrderDateKey

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation PBI_ChangedProperties = ["IsHidden"]

	column DueDateKey
		dataType: int64
		isHidden
		formatString: 0
		summarizeBy: none
		sourceColumn: DueDateKey

		annotation SummarizationSetBy = User

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation PBI_ChangedProperties = ["IsHidden"]

	column ShipDateKey
		dataType: int64
		isHidden
		formatString: 0
		summarizeBy: none
		sourceColumn: ShipDateKey

		annotation SummarizationSetBy = User

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation PBI_ChangedProperties = ["IsHidden"]

	column SalesTerritoryKey
		dataType: int64
		isHidden
		formatString: 0
		summarizeBy: none
		sourceColumn: SalesTerritoryKey

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation PBI_ChangedProperties = ["IsHidden"]

	column 'Order Quantity'
		dataType: int64
		formatString: #,0
		summarizeBy: none
		sourceColumn: Order Quantity

		annotation SummarizationSetBy = User

		annotation Format = <Format Format="NumberWhole" Accuracy="0" ThousandSeparator="True" />

	column 'Unit Price'
		dataType: decimal
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		summarizeBy: none
		sourceColumn: Unit Price

		annotation SummarizationSetBy = User

		annotation Format = <Format Format="CurrencyCustom" Accuracy="2" ThousandSeparator="True"><Currency LCID="1033" DisplayName="$ English (United States)" Symbol="$" PositivePattern="0" NegativePattern="0" /></Format>

	column 'Extended Amount'
		dataType: decimal
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		summarizeBy: none
		sourceColumn: Extended Amount

		annotation SummarizationSetBy = User

		annotation Format = <Format Format="CurrencyCustom" Accuracy="2" ThousandSeparator="True"><Currency LCID="1033" DisplayName="$ English (United States)" Symbol="$" PositivePattern="0" NegativePattern="0" /></Format>

	column 'Product Standard Cost'
		dataType: decimal
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		summarizeBy: none
		sourceColumn: Product Standard Cost

		annotation SummarizationSetBy = User

		annotation Format = <Format Format="CurrencyCustom" Accuracy="2" ThousandSeparator="True"><Currency LCID="1033" DisplayName="$ English (United States)" Symbol="$" PositivePattern="0" NegativePattern="0" /></Format>

	column 'Total Product Cost'
		dataType: decimal
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		summarizeBy: none
		sourceColumn: Total Product Cost

		annotation SummarizationSetBy = User

		annotation Format = <Format Format="CurrencyCustom" Accuracy="2" ThousandSeparator="True"><Currency LCID="1033" DisplayName="$ English (United States)" Symbol="$" PositivePattern="0" NegativePattern="0" /></Format>

	column 'Sales Amount'
		dataType: decimal
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		summarizeBy: none
		sourceColumn: Sales Amount

		annotation SummarizationSetBy = User

		annotation Format = <Format Format="CurrencyCustom" Accuracy="2" ThousandSeparator="True"><Currency LCID="1033" DisplayName="$ English (United States)" Symbol="$" PositivePattern="0" NegativePattern="0" /></Format>

	column 'Unit Price Discount Pct'
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		summarizeBy: none
		sourceColumn: Unit Price Discount Pct

		annotation SummarizationSetBy = User

		annotation Format = <Format Format="Percentage" Accuracy="2" />

	partition Sales-1c496a38-f0f4-4d25-b987-657177c38553 = m
		mode: import
		source =
				let
				    Source = Sql.Database(SqlServerInstance, SqlServerDatabase),
				    dbo_vFactSales = Source{[Schema="dbo",Item="vFactSales"]}[Data],
				    #"Removed Other Columns" = Table.SelectColumns(dbo_vFactSales,{"SalesOrderLineKey", "ResellerKey", "CustomerKey", "ProductKey", "OrderDateKey", "DueDateKey", "ShipDateKey", "SalesTerritoryKey", "OrderQuantity", "UnitPrice", "ExtendedAmount", "UnitPriceDiscountPct", "ProductStandardCost", "TotalProductCost", "SalesAmount"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Other Columns",{{"OrderQuantity", Int64.Type}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"ExtendedAmount", "Extended Amount"}, {"OrderQuantity", "Order Quantity"}, {"ProductStandardCost", "Product Standard Cost"}, {"SalesAmount", "Sales Amount"}, {"TotalProductCost", "Total Product Cost"}, {"UnitPrice", "Unit Price"}, {"UnitPriceDiscountPct", "Unit Price Discount Pct"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

