table 'Sales Order'

	column SalesOrderLineKey
		dataType: int64
		isHidden
		formatString: 0
		summarizeBy: none
		sourceColumn: SalesOrderLineKey

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation PBI_ChangedProperties = ["IsHidden"]

	column 'Sales Order'
		dataType: string
		summarizeBy: none
		sourceColumn: Sales Order

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

	column 'Sales Order Line'
		dataType: string
		isDefaultLabel
		summarizeBy: none
		sourceColumn: Sales Order Line
		sortByColumn: SalesOrderLineKey

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

	column Channel
		dataType: string
		summarizeBy: none
		sourceColumn: Channel

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

	hierarchy 'Sales Orders'

		level 'Sales Order'
			column: 'Sales Order'

		level 'Sales Order Line'
			column: 'Sales Order Line'

	partition 'Sales Order-3ce1b467-3e1b-4732-b605-3e94fee75991' = m
		mode: import
		source =
				let
				    Source = Sql.Database(SqlServerInstance, SqlServerDatabase),
				    dbo_vFactSales = Source{[Schema="dbo",Item="vFactSales"]}[Data],
				    #"Removed Other Columns" = Table.SelectColumns(dbo_vFactSales,{"Channel", "SalesOrderLineKey", "SalesOrderNumber", "SalesOrderLineNumber"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Other Columns",{{"SalesOrderNumber", "Sales Order"}}),
				    #"Added Custom" = Table.AddColumn(#"Renamed Columns", "Sales Order Line", each [Sales Order] & " - " & Text.PadStart(Number.ToText([SalesOrderLineNumber]), 2, "0")),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Custom",{{"Sales Order Line", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"SalesOrderLineNumber"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

